FROM node:22-alpine3.19

RUN adduser --disabled-password --gecos '' sagedsama --uid 10001

USER 10001

WORKDIR /app/frontend

COPY . .
RUN npm install

ENV PUBLIC_API_URL=http://localhost:8080
ENV PUBLIC_API_WS=ws://localhost:8080/ws

RUN npm run build

CMD [ "node", "build" ]