name: "ppsharefiles"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_URL=http://backend:8080
      - PUBLIC_API_WS=ws://backend:8080/ws
    depends_on:
      - backend
    command: ["node", "build"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8080
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
