FROM python:3.12.6-slim-bookworm

RUN adduser --disabled-password --gecos '' sagedsama --uid 10001

USER 10001

WORKDIR /app/backend

COPY requirements.txt .

# RUN python -m venv env

# RUN /bin/bash -c "source env/bin/activate"

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]